### ISSUE TITLE
Life after APIStar 0.5

### ISSUE THREAD

**Issue by rhelms** [audiolion/apistar-jwt#20]
Given the refined direction that apistar has taken with 0.6, will this repo be likely to stick around?

I've a few apistar containers running 0.5.42 that are not likely to receive any major updates other than introduction of JWT for authentication. This package seems to fit the bill nicely, and rather than write something same-same-but-different or clone the repo, it would be good to know the future of this repo.

I noticed travis doesn't have an end point, so thought I'd ask the question as to if that was the direction of this package.

**Comment by audiolion** [comment]
hey @rhelms, after apistar changed direction quite radically, I decided to not continue with this package. I haven't added a notice though and I should, I would recommend, if you liked api star as it was, to use [Molten](https://moltenframework.com/) which has [Molten JWT](https://github.com/androiddrew/molten-jwt) by @androiddrew which is similar to this package

**Comment by rhelms** [comment]
Cheers for the update.
I'm relatively new to Python (only a couple of years out of my 20+ years of programming), and Django is all I had been using up until API Star. I did take a look at Molten, but we're likely to move to Flask-RESTPlus for lightweight REST processing.
I was hoping to avoid doing that conversion for this particular task, but the more I think about it, the more illogical it seems to be not to migrate away (other than the cost of development for refitting the typesystem, compared with the goal at hand, which was just to introduce JWT).
