### ISSUE TITLE
Working Example?

### ISSUE THREAD

**Issue by juancarlospaco** [audiolion/apistar-jwt#5]
Should be nice to have a working Example, something that people can just download and run.

The framework is new, I am using it for some time and yet I dont understand how to use Apistar-JWT, 
should I use as Component?, or not?, or both at the same time can be used?, Pros Vs Cons of using it as Component?, 
JWT supports passing Token on URL or POST args, does apistar-jwt supports that?,
I read the tests, but actually implementing it on the code just from reading the tests and readme seems complicated.

At least 1 minimal working example should be very useful and bring more users to the project.
Just a `/example/app.py`
[Ive created the same for my Apistar components](https://github.com/juancarlospaco/apistar-session-cookie/blob/master/example/app.py)

Keep it up!, is a great project!. :smile_cat:

**Comment by audiolion** [comment]
sure ill add one, thanks for the suggestion!
